# Kuragayala Kenny Joel Numpy

In this Machine Learning Lab - 1. I have explored various and played around the numpy library.




**Report**


The numpy libeary helps in various kinds of getting random values and helps in calculating also.


-> Helps in generating random numbers.


-> Helps in reshaping the array


-> Helps in find mathematical oycomes like logarithms, Square roots.


-> We can play with all these

In [1]:
#importing numpy
import numpy as np
from timeit import default_timer as timer

In [2]:
#importing random values
a  = np.random.randint(9, size=(100))

In [3]:
print(a) # just shows all elements

[7 0 3 1 2 7 0 2 6 0 7 6 2 8 4 3 1 0 0 4 5 4 7 5 8 3 1 0 5 0 7 3 1 2 3 0 7
 4 6 2 6 1 7 8 3 0 1 7 2 4 2 5 2 4 4 0 0 7 1 3 4 6 1 3 0 3 5 6 3 3 2 1 0 1
 6 0 3 7 7 1 6 2 7 1 3 4 0 5 5 2 5 2 8 0 3 2 6 2 3 8]


In [4]:
print(a.shape) # shows the shape based on element (3,)

(100,)


In [5]:
print(a.dtype) # shows the datatype int 32 or int 64

int32


In [6]:
print(a.ndim) #shows the dimension, here it is one dimension

1


In [7]:
print(a.size) #shows the length of array based on elements

100


In [8]:
print(a.itemsize) #each element ina array has 4 or 8 bytes

4


In [9]:
print(a[0]) #accesing element thru index position

7


In [10]:
b=a+np.array([4]) #here we are adding 4 lets see this operation. this is called boradcasting method or use a=a+np.array([4,4,4])
print(b) # observe here it is adding 4 to every elemtn in array [5 6 7]

[11  4  7  5  6 11  4  6 10  4 11 10  6 12  8  7  5  4  4  8  9  8 11  9
 12  7  5  4  9  4 11  7  5  6  7  4 11  8 10  6 10  5 11 12  7  4  5 11
  6  8  6  9  6  8  8  4  4 11  5  7  8 10  5  7  4  7  9 10  7  7  6  5
  4  5 10  4  7 11 11  5 10  6 11  5  7  8  4  9  9  6  9  6 12  4  7  6
 10  6  7 12]


In [11]:
#any operations on array operate element wise
c=np.sqrt(a)
print(c)

[2.64575131 0.         1.73205081 1.         1.41421356 2.64575131
 0.         1.41421356 2.44948974 0.         2.64575131 2.44948974
 1.41421356 2.82842712 2.         1.73205081 1.         0.
 0.         2.         2.23606798 2.         2.64575131 2.23606798
 2.82842712 1.73205081 1.         0.         2.23606798 0.
 2.64575131 1.73205081 1.         1.41421356 1.73205081 0.
 2.64575131 2.         2.44948974 1.41421356 2.44948974 1.
 2.64575131 2.82842712 1.73205081 0.         1.         2.64575131
 1.41421356 2.         1.41421356 2.23606798 1.41421356 2.
 2.         0.         0.         2.64575131 1.         1.73205081
 2.         2.44948974 1.         1.73205081 0.         1.73205081
 2.23606798 2.44948974 1.73205081 1.73205081 1.41421356 1.
 0.         1.         2.44948974 0.         1.73205081 2.64575131
 2.64575131 1.         2.44948974 1.41421356 2.64575131 1.
 1.73205081 2.         0.         2.23606798 2.23606798 1.41421356
 2.23606798 1.41421356 2.82842712 0.         1.7320

In [12]:
d=np.log(a)
print(d)

[1.94591015       -inf 1.09861229 0.         0.69314718 1.94591015
       -inf 0.69314718 1.79175947       -inf 1.94591015 1.79175947
 0.69314718 2.07944154 1.38629436 1.09861229 0.               -inf
       -inf 1.38629436 1.60943791 1.38629436 1.94591015 1.60943791
 2.07944154 1.09861229 0.               -inf 1.60943791       -inf
 1.94591015 1.09861229 0.         0.69314718 1.09861229       -inf
 1.94591015 1.38629436 1.79175947 0.69314718 1.79175947 0.
 1.94591015 2.07944154 1.09861229       -inf 0.         1.94591015
 0.69314718 1.38629436 0.69314718 1.60943791 0.69314718 1.38629436
 1.38629436       -inf       -inf 1.94591015 0.         1.09861229
 1.38629436 1.79175947 0.         1.09861229       -inf 1.09861229
 1.60943791 1.79175947 1.09861229 1.09861229 0.69314718 0.
       -inf 0.         1.79175947       -inf 1.09861229 1.94591015
 1.94591015 0.         1.79175947 0.69314718 1.94591015 0.
 1.09861229 1.38629436       -inf 1.60943791 1.60943791 0.69314718
 1.60943791 0.69314

C:\Users\pc\AppData\Local\Temp/ipykernel_8884/4102135006.py:1: RuntimeWarning: divide by zero encountered in log
  d=np.log(a)


In [13]:
#dot product demo
dot = 0 #temp variable
for i in range(len(a)):
    dot+=a[i]*b[i]
print(dot) #prints but not clear lets make more clear

3135


In [14]:
#speed test to understand which performs best lists or arrays
A = np.random.randint(99, size=(1000)) #useful in converting numpy array in to list using list() funtion
B = np.random.randint(99, size=(1000))

T = 10000  #to cal. dot product 10000 times

In [15]:
# two ways  -> one using manual in for loops & other using np.dot instance function using single line
def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i] * B[i]
    return dot

In [16]:
def dot2():
    return np.dot(a,b)

In [17]:
start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start

In [18]:
start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start

In [19]:
# observe your time differences took to compute
print("list computation took",t1)

list computation took 2.4689927


In [20]:
print('np.dot', t2)

np.dot 0.023135800000000373


In [21]:
print('ratio', t1/t2) #so numpy is XX.XX times faster for math operations

ratio 106.71741197624289


In [22]:
e  = np.random.randint(9, size=(2, 3))
print(e)

[[5 7 5]
 [2 2 7]]


In [23]:
print(e.shape) # 2 rows and 3 cols

(2, 3)


In [24]:
print(e[0][0])  #or we can write short form as print(a[0,0])

5


In [25]:
print(e[:,0]) # return all row elements in col 0. 

[5 2]


In [26]:
print(e[0,:]) # prints whole first row

[5 7 5]


In [27]:
print(e.T) # perform transpose operation

[[5 2]
 [7 2]
 [5 7]]


In [28]:
f = np.random.randint(9, size=(2, 2))
f

array([[1, 7],
       [5, 6]])

In [29]:
print(np.linalg.inv(f)) #inverse operation

[[-0.20689655  0.24137931]
 [ 0.17241379 -0.03448276]]


In [30]:
print(np.linalg.det(f)) # det operation

-28.99999999999999


In [31]:
print(np.diag(f)) #returns diagnol ele of array b here


[1 6]


In [32]:
e = np.diag(f)
print(np.diag(e)) #returns diag ele and others showing 0.

[[1 0]
 [0 6]]


In [33]:
a  = np.random.randint(9, size=(2, 3))
print(a)

[[2 4 8]
 [2 3 3]]


In [34]:
b = a[0,1]  # based on indexing
print(b)

4


In [35]:
b = a[0,1:3] #in first row, it takes only first 2 elements and excludes last elem. as in the slicing
print(b)

[4 8]


In [36]:
b = a[:,0] #incase of first cols
print(b)

[2 2]


In [37]:
b = a[-1,-1] #using indices in -ve, incase to start from end. so last row, last col
print(b)

3


In [38]:
b = a[-1,-2] #incase to start from end. so last row, 2nd col from end
print(b)

3
